// <auto-generated />
namespace Internet_shops.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Db3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Db3));
        
        string IMigrationMetadata.Id
        {
            get { return "202205171302501_Db3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
